spring.application.name=pugs
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

aws.secret.key=${AWS_SECRET}
aws.access.key=${AWS_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.bucket.name=${AWS_BUCKET_NAME}

admin.password.init=${ADMIN_PASS}
admin.email.init=${ADMIN_EMAIL}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}